const API = (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1')
    ? 'http://localhost:3001/api'
    : `${window.location.origin}/api`;
const S = {
    lang: localStorage.getItem('lang') || 'ar',
    theme: localStorage.getItem('theme') || 'light',
    trade: null, stack: [], cats: [], prods: [], pCache: {},
    cart: JSON.parse(localStorage.getItem('cart') || '[]'),
    wish: JSON.parse(localStorage.getItem('wish') || '[]'),
    coupon: null, shipping: [], cfg: {},
    curProd: null, selColor: null, selSize: null, payMethod: 'cash',
    waData: null, user: JSON.parse(localStorage.getItem('user') || 'null'), deferredPrompt: null,
};
const TEXTS = {
    ar: { home: 'الرئيسية', back: 'رجوع', add: 'إضافة للسلة', no_size: 'اختر مقاس أولاً', colors: 'الألوان', sizes: 'المقاسات', no_res: 'لا توجد منتجات', search_ph: 'ابحث عن منتج...', cart_t: 'السلة 🛍️', empty: 'سلتك فارغة!', checkout: 'إتمام الطلب ←', order_t: 'إتمام الطلب', n_name: 'الاسم الكامل *', n_phone: 'رقم الهاتف *', n_phone2: 'رقم إضافي', n_gov: 'المحافظة *', n_addr: 'العنوان *', n_pay: 'طريقة الدفع', cash: 'كاش عند الاستلام', online: 'أون لاين (فيزا)', place: 'تأكيد الطلب', placing: 'جاري الإرسال...', suc_t: 'تم الطلب!', suc_m: 'شكراً! طلبك وصلنا وهنتواصل معاك', wish_t: 'المفضلة ❤️', wish_empty: 'مفضلتك فارغة', retail: 'قطاعي', retail_d: 'تسوق للأفراد', wholesale: 'جملة', wholesale_d: 'أسعار الجملة للتجار' },
    en: { home: 'Home', back: 'Back', add: 'Add to Cart', no_size: 'Choose size first', colors: 'Colors', sizes: 'Sizes', no_res: 'No products found', search_ph: 'Search products...', cart_t: 'Cart 🛍️', empty: 'Cart is empty!', checkout: 'Checkout →', order_t: 'Complete Order', n_name: 'Full Name *', n_phone: 'Phone *', n_phone2: 'Extra Phone', n_gov: 'Governorate *', n_addr: 'Address *', n_pay: 'Payment', cash: 'Cash on Delivery', online: 'Online (Visa)', place: 'Confirm Order', placing: 'Sending...', suc_t: 'Order Placed!', suc_m: 'Thank you! Your order is received.', wish_t: 'Wishlist ❤️', wish_empty: 'Wishlist empty', retail: 'Retail', retail_d: 'Shop for individuals', wholesale: 'Wholesale', wholesale_d: 'Wholesale prices', }
};
const t = k => TEXTS[S.lang][k] || k;

/* INTRO */
(() => {
    const c = document.getElementById('pcan'), ctx = c.getContext('2d');
    let W, H, pts = [], animId;
    function resize() { W = c.width = innerWidth; H = c.height = innerHeight; }
    resize(); window.addEventListener('resize', resize);
    for (let i = 0; i < 300; i++) { const a = Math.random() * Math.PI * 2, r = Math.random() * Math.min(W, H) * .5; pts.push({ x: W / 2 + Math.cos(a) * r, y: H / 2 + Math.sin(a) * r, a, r, spd: Math.random() * .008 + .003, sz: Math.random() * 2 + .5, col: Math.random() > .5 ? `rgba(200,25,30,${Math.random() * .7 + .2})` : `rgba(212,160,23,${Math.random() * .7 + .2})` }); }
    let phase = 0, prog = 0;
    function draw() {
        ctx.fillStyle = phase < 2 ? 'rgba(0,0,0,.08)' : 'rgba(0,0,0,.16)';
        ctx.fillRect(0, 0, W, H);
        if (phase === 0) { pts.forEach(p => { p.a += p.spd * (1 + prog * 3); p.x = W / 2 + Math.cos(p.a) * p.r; p.y = H / 2 + Math.sin(p.a) * p.r; ctx.beginPath(); ctx.arc(p.x, p.y, p.sz, 0, Math.PI * 2); ctx.fillStyle = p.col; ctx.fill(); }); }
        else if (phase === 2) { pts.forEach(p => { const dx = p.x - W / 2, dy = p.y - H / 2, d = Math.sqrt(dx * dx + dy * dy), s = d * .08; p.x += dx / d * s; p.y += dy / d * s; ctx.beginPath(); ctx.moveTo(p.x - dx * .3, p.y - dy * .3); ctx.lineTo(p.x, p.y); ctx.strokeStyle = p.col; ctx.lineWidth = p.sz; ctx.stroke(); }); }
        animId = requestAnimationFrame(draw);
    }
    draw();
    let bp = 0;
    const bi = setInterval(() => {
        bp += Math.random() * 4 + 1; if (bp > 100) bp = 100; prog = bp / 100;
        const bar = document.getElementById('ibar'); if (bar) bar.style.width = bp + '%';
        if (bp >= 100) {
            clearInterval(bi); phase = 1;
            const fl = document.getElementById('iflash'); fl.style.opacity = '1';
            setTimeout(() => {
                fl.style.transition = 'opacity .5s'; fl.style.opacity = '0';
                const ring = document.getElementById('iring'); ring.style.transition = 'all .8s cubic-bezier(.175,.885,.32,1.275)'; ring.style.opacity = '1'; ring.style.transform = 'scale(1)';
                const brand = document.getElementById('ibrand'); brand.style.transition = 'all .7s ease .3s'; brand.style.opacity = '1'; brand.style.transform = 'none';
                const sub = document.getElementById('isub'); sub.style.transition = 'all .6s ease .5s'; sub.style.opacity = '1';
                setTimeout(() => { phase = 2; setTimeout(skipIntro, 900); }, 900);
            }, 200);
        }
    }, 55);
    window.skipIntro = () => { clearInterval(bi); cancelAnimationFrame(animId); gsap.to('#intro', { opacity: 0, scale: 1.1, duration: .55, ease: 'power2.in', onComplete: () => { document.getElementById('intro').style.display = 'none'; startApp(); } }); };
})();

/* START */
async function startApp() { applyTheme(); applyLang(); updateBadges(); await loadCfg(); await loadShipping(); fillGovs(); initChat(); window.addEventListener('beforeinstallprompt', e => { e.preventDefault(); S.deferredPrompt = e; const b = document.getElementById('pwa-btn'); b.style.display = 'inline-flex'; b.onclick = async () => { S.deferredPrompt.prompt(); S.deferredPrompt = null; }; }); }

/* CONFIG */
async function loadCfg() { try { const r = await fetch(`${API}/settings`); S.cfg = await r.json(); const ab = document.getElementById('ann-bar'); if (S.cfg.announcement_active === 'true' && S.cfg.announcement_text && !sessionStorage.getItem('ann-closed')) { document.getElementById('ann-text').textContent = S.cfg.announcement_text; ab.classList.add('on'); document.body.classList.add('has-ann'); document.getElementById('main-hd').style.top = '40px'; } if (S.cfg.maintenance_mode === 'true') { document.getElementById('maint-reason').textContent = S.cfg.maintenance_reason || ''; document.getElementById('maint-dur').textContent = S.cfg.maintenance_duration || ''; document.getElementById('maint').classList.add('on'); } } catch (e) { } }
function closeAnn() { document.getElementById('ann-bar').classList.remove('on'); document.body.classList.remove('has-ann'); document.getElementById('main-hd').style.top = ''; sessionStorage.setItem('ann-closed', '1'); }
async function loadShipping() { try { const r = await fetch(`${API}/shipping`); S.shipping = await r.json(); } catch (e) { } }
function fillGovs() { const sel = document.getElementById('of-gov'); sel.innerHTML = '<option value="">اختر المحافظة</option>'; S.shipping.forEach(r => { const o = document.createElement('option'); o.value = r.governorate; o.textContent = r.governorate; sel.appendChild(o); }); }

/* THEME / LANG */
function applyTheme() { if (S.theme === 'dark') document.body.classList.add('dark'); else document.body.classList.remove('dark'); document.getElementById('theme-btn').textContent = S.theme === 'dark' ? '☀️' : '🌙'; }
function toggleTheme() { S.theme = S.theme === 'dark' ? 'light' : 'dark'; localStorage.setItem('theme', S.theme); applyTheme(); }
function applyLang() { const ar = S.lang === 'ar'; document.documentElement.lang = S.lang; document.documentElement.dir = ar ? 'rtl' : 'ltr'; document.getElementById('lang-btn').textContent = ar ? 'EN' : 'AR'; const m = { 'trade-sub': ar ? 'اختر نوع التسوق' : 'Choose Shopping Type', 'tc-retail': t('retail'), 'tc-retail-d': t('retail_d'), 'tc-wholesale': t('wholesale'), 'tc-wholesale-d': t('wholesale_d'), 'back-lbl': t('back'), 'cart-title': t('cart_t'), 'order-title': t('order_t'), 'lbl-name': t('n_name'), 'lbl-phone': t('n_phone'), 'lbl-phone2': t('n_phone2'), 'lbl-gov': t('n_gov'), 'lbl-addr': t('n_addr'), 'lbl-pay': t('n_pay'), 'pay-cash-lbl': t('cash'), 'pay-online-lbl': t('online'), 'add-lbl': t('add'), 'color-lbl': t('colors'), 'size-lbl': t('sizes'), 'wish-title': t('wish_t'), 'suc-title': t('suc_t'), 'suc-msg': t('suc_m') }; for (const [id, val] of Object.entries(m)) { const el = document.getElementById(id); if (el && val) el.textContent = val; } const si = document.getElementById('search-inp'); if (si) si.placeholder = t('search_ph'); }
function toggleLang() { S.lang = S.lang === 'ar' ? 'en' : 'ar'; localStorage.setItem('lang', S.lang); applyLang(); rerender(); }

/* NAV */
function goHome() { S.stack = []; S.trade = null; show('trade-sel'); hide('cats-view'); hide('prods-view'); document.getElementById('bc').classList.remove('show'); }
function selectTrade(tr) { S.trade = tr; S.stack = [{ type: 'root', name: tr === 'retail' ? 'قطاعي' : 'ج jmlة' }]; loadCats(null); }
async function loadCats(pid) { hide('trade-sel'); hide('prods-view'); show('cats-view'); document.getElementById('cats-view').innerHTML = '<div class="spin"></div>'; updateBC(); try { const r = await fetch(`${API}/categories`); S.cats = await r.json(); const kids = S.cats.filter(c => pid ? c.parent_id == pid : !c.parent_id); if (!kids.length && pid) { await showProds(pid, S.stack[S.stack.length - 1]?.name || ''); return; } document.getElementById('cats-view').innerHTML = (pid ? `<div class="sec-head"><button class="back-btn" onclick="goBack()">⬅ ${t('back')}</button><div class="sec-title">${S.stack[S.stack.length - 1]?.name || ''}</div></div>` : '') + `<div class="cats-grid">${kids.map(c => { const name = S.lang === 'ar' ? c.name_ar : (c.name_en || c.name_ar); return `<div class="cat-card" onclick="navInto(${c.id},'${name}')"><div class="cc-icon">${catIcon(c.name_ar)}</div><div class="cc-name">${name}</div></div>`; }).join('')}</div>`; } catch (e) { document.getElementById('cats-view').innerHTML = '<p style="text-align:center;padding:50px;color:var(--text2)">خطأ في التحميل</p>'; } }
function catIcon(n) { const m = { 'رجالي': '👔', 'حريمي': '👗', 'أطفال': '👶', 'رياضي': '🏃', 'تيشرتات': '👕', 'بناطيل': '👖', 'فساتين': '👘', 'أحذية': '👟', 'شنط': '👜', 'اكسسوارات': '💍', 'جاكيتات': '🧥' }; return Object.entries(m).find(([k]) => n.includes(k))?.[1] || '🏷️'; }
async function navInto(id, name) { S.stack.push({ type: 'cat', id, name }); const r = await fetch(`${API}/products?category_id=${id}`); const ps = await r.json(); const hasSubs = S.cats.some(c => c.parent_id == id); if (ps.length > 0 && !hasSubs) showProds(id, name); else loadCats(id); }
function goBack() { if (S.stack.length <= 1) { goHome(); return; } S.stack.pop(); const top = S.stack[S.stack.length - 1]; if (top.type === 'root') loadCats(null); else loadCats(top.id); }
function updateBC() { const bc = document.getElementById('bc'); if (!S.stack.length) { bc.classList.remove('show'); return; } bc.classList.add('show'); bc.innerHTML = `<span class="bc-item" onclick="goHome()">🏠 ${t('home')}</span>` + S.stack.map((n, i) => `<span class="bc-sep">›</span><span class="bc-item ${i === S.stack.length - 1 ? 'cur' : ''}" onclick="bcGo(${i})">${n.name}</span>`).join(''); }
function bcGo(i) { const n = S.stack[i]; S.stack = S.stack.slice(0, i + 1); n.type === 'root' ? loadCats(null) : loadCats(n.id); }
function rerender() { applyLang(); if (S.trade) { const top = S.stack[S.stack.length - 1]; if (document.getElementById('prods-view').style.display !== 'none') renderProds(S.prods); else if (top?.type === 'root') loadCats(null); else if (top) loadCats(top.id); } }

async function showProds(catId, title) { hide('cats-view'); show('prods-view'); document.getElementById('prods-title').textContent = title; document.getElementById('search-inp').value = ''; updateBC(); renderSibNav(catId); if (S.pCache[catId]) { S.prods = S.pCache[catId]; renderProds(S.prods); return; } const g = document.getElementById('prods-grid'); g.innerHTML = Array(6).fill(`<div class="skel" style="height:320px"></div>`).join(''); try { const r = await fetch(`${API}/products?category_id=${catId}`); S.prods = await r.json(); S.pCache[catId] = S.prods; renderProds(S.prods); } catch (e) { g.innerHTML = '<p style="text-align:center;padding:50px;color:var(--text2)">خطأ في التحميل</p>'; } }
function renderSibNav(cur) { const nav = document.getElementById('sib-nav'); const cc = S.cats.find(c => c.id == cur); if (!cc) { nav.innerHTML = ''; return; } const sibs = S.cats.filter(c => c.parent_id == cc.parent_id && c.parent_id); if (sibs.length < 2) { nav.innerHTML = ''; return; } nav.innerHTML = sibs.map(s => { const name = S.lang === 'ar' ? s.name_ar : (s.name_en || s.name_ar); return `<div class="sib-chip ${s.id == cur ? 'on' : ''}" onclick="navTo(${s.id},'${name}')">${name}</div>`; }).join(''); }
function navTo(id, name) { S.stack[S.stack.length - 1] = { type: 'cat', id, name }; showProds(id, name); }
function renderProds(ps) { const g = document.getElementById('prods-grid'); const base = API.replace('/api', ''); if (!ps.length) { g.innerHTML = `<div class="no-res"><div class="no-res-icon">🔍</div><p>${t('no_res')}</p></div>`; return; } g.innerHTML = ps.map(p => { const name = S.lang === 'ar' ? p.name_ar : (p.name_en || p.name_ar); const inW = S.wish.some(w => w.id == p.id); return `<div class="prod-card" onclick="openProd(${p.id})"><div class="prod-img">${p.main_image ? `<img data-src="${base}${p.main_image}" src="" class="lazy" alt="${name}">` : `<div class="prod-ph">👕</div>`}${p.main_color_ar ? `<span class="color-badge">${S.lang === 'ar' ? p.main_color_ar : (p.main_color_en || p.main_color_ar)}</span>` : ''}<button class="wish-btn ${inW ? 'on' : ''}" onclick="event.stopPropagation();quickWish(${p.id})">${inW ? '❤️' : '🤍'}</button></div><div class="prod-info"><div class="prod-name">${name}</div><div class="prod-price">${p.price.toFixed(0)} ج.م</div><div class="prod-sku">${p.sku}</div></div></div>`; }).join(''); const obs = new IntersectionObserver(es => { es.forEach(e => { if (e.isIntersecting) { e.target.src = e.target.dataset.src; obs.unobserve(e.target); } }); }); document.querySelectorAll('.lazy').forEach(img => obs.observe(img)); }
function searchProds(q) { if (!q) { renderProds(S.prods); return; } renderProds(S.prods.filter(p => p.name_ar.includes(q) || (p.name_en || '').toLowerCase().includes(q.toLowerCase()))); }
function clearSearch() { document.getElementById('search-inp').value = ''; renderProds(S.prods); }

/* PRODUCT MODAL */
function openProd(id) { const p = S.prods.find(x => x.id == id); if (!p) return; S.curProd = p; S.selColor = null; S.selSize = null; const base = API.replace('/api', ''); const name = S.lang === 'ar' ? p.name_ar : (p.name_en || p.name_ar); document.getElementById('modal-name').textContent = name; document.getElementById('modal-sku').textContent = p.sku; document.getElementById('modal-price').textContent = `${p.price.toFixed(0)} ج.م`; const img = document.getElementById('modal-img'), ph = document.getElementById('modal-img-ph'); if (p.main_image) { img.src = base + p.main_image; img.style.display = 'block'; ph.style.display = 'none'; } else { img.style.display = 'none'; ph.style.display = 'flex'; } const allC = getColors(p); const cs = document.getElementById('colors-sec'); if (allC.length > 1) { cs.style.display = 'block'; document.getElementById('modal-colors').innerHTML = allC.map((c, i) => `<button class="dchip ${i === 0 ? 'on' : ''}" onclick="selColorFn(${i})">${S.lang === 'ar' ? c.ar : c.en}</button>`).join(''); S.selColor = 0; renderSizes(allC[0].sizes); } else { cs.style.display = 'none'; renderSizes(p.sizes || []); } document.getElementById('modal-desc').textContent = p.description || ''; document.getElementById('modal-wish').classList.toggle('on', S.wish.some(w => w.id == p.id)); updateAddBtn(); openModal('prod-modal'); }
function getColors(p) { const a = []; if (p.main_color_ar) a.push({ ar: p.main_color_ar, en: p.main_color_en || p.main_color_ar, image: p.main_image, sizes: p.sizes || [] }); if (p.variants?.length) p.variants.forEach(v => a.push({ ar: v.color_ar || v.color, en: v.color_en || v.color, image: v.image, sizes: v.sizes || [] })); return a; }
function selColorFn(i) { S.selColor = i; S.selSize = null; document.querySelectorAll('#modal-colors .dchip').forEach((c, x) => c.classList.toggle('on', x === i)); const col = getColors(S.curProd)[i]; const base = API.replace('/api', ''); const img = document.getElementById('modal-img'); if (col.image) { img.src = base + col.image; img.style.display = 'block'; document.getElementById('modal-img-ph').style.display = 'none'; } renderSizes(col.sizes || []); updateAddBtn(); }
function renderSizes(sizes) { const w = document.getElementById('sizes-sec'); if (!sizes?.length) { w.style.display = 'none'; return; } w.style.display = 'block'; document.getElementById('modal-sizes').innerHTML = sizes.map(s => `<button class="dchip" onclick="selSizeFn('${s}')">${s}</button>`).join(''); }
function selSizeFn(s) { S.selSize = s; document.querySelectorAll('#modal-sizes .dchip').forEach(c => c.classList.toggle('on', c.textContent === s)); updateAddBtn(); }
function updateAddBtn() { const p = S.curProd; const needSize = (p.sizes || []).length > 0; const btn = document.getElementById('add-btn'); const lbl = document.getElementById('add-lbl'); if (needSize && !S.selSize) { lbl.textContent = t('no_size'); btn.disabled = true; } else { lbl.textContent = t('add'); btn.disabled = false; } }
function toggleModalWish() { quickWish(S.curProd.id); document.getElementById('modal-wish').classList.toggle('on', S.wish.some(w => w.id == S.curProd.id)); }
function addToCart() { const p = S.curProd; const name = S.lang === 'ar' ? p.name_ar : (p.name_en || p.name_ar); const cols = getColors(p); const col = cols[S.selColor ?? 0] || null; const key = `${p.id}-${col?.ar || ''}-${S.selSize || ''}`; const ex = S.cart.find(i => i.key === key); if (ex) ex.qty++; else S.cart.push({ key, id: p.id, name, sku: p.sku, price: p.price, color: col ? (S.lang === 'ar' ? col.ar : col.en) : null, size: S.selSize, image: col?.image || p.main_image, qty: 1 }); saveCart(); updateBadges(); closeModal('prod-modal'); toast(t('add') + ' ✓', 'ok'); }

/* CART */
function openCart() { renderCart(); document.getElementById('cart-drawer').classList.add('on'); document.getElementById('drw-bg').classList.add('on'); }
function closeCart() { document.getElementById('cart-drawer').classList.remove('on'); document.getElementById('drw-bg').classList.remove('on'); }
function renderCart() { const el = document.getElementById('cart-items'); const base = API.replace('/api', ''); if (!S.cart.length) { el.innerHTML = `<div class="empty-cart"><div class="empty-icon">🛒</div><p>${t('empty')}</p></div>`; updateTotals(); return; } el.innerHTML = S.cart.map(i => `<div class="ci"><div class="ci-img">${i.image ? `<img src="${base}${i.image}" alt="">` : ''}</div><div class="ci-info"><div class="ci-name">${i.name}</div><div class="ci-meta">${i.sku}${i.color ? ' | ' + i.color : ''}${i.size ? ' | ' + i.size : ''}</div><div class="ci-price">${(i.price * i.qty).toFixed(0)} ج.م</div><div class="ci-qty"><button class="qty-btn" onclick="chQty('${i.key}',-1)">−</button><span>${i.qty}</span><button class="qty-btn" onclick="chQty('${i.key}',1)">+</button></div></div><button class="ci-del" onclick="removeCI('${i.key}')">🗑️</button></div>`).join(''); updateTotals(); }
function chQty(key, d) { const i = S.cart.find(x => x.key === key); if (!i) return; i.qty += d; if (i.qty <= 0) S.cart = S.cart.filter(x => x.key !== key); saveCart(); updateBadges(); renderCart(); }
function removeCI(key) { S.cart = S.cart.filter(x => x.key !== key); saveCart(); updateBadges(); renderCart(); }
function saveCart() { localStorage.setItem('cart', JSON.stringify(S.cart)); }
function updateTotals() { const sub = S.cart.reduce((s, i) => s + i.price * i.qty, 0); const disc = S.coupon ? (S.coupon.type === 'percent' ? sub * S.coupon.value / 100 : S.coupon.value) : 0; document.getElementById('cart-sub').textContent = sub.toFixed(0) + ' ج.م'; const dr = document.getElementById('disc-row'); if (disc > 0) { dr.style.display = 'flex'; document.getElementById('cart-disc').textContent = disc.toFixed(0) + ' ج.م-'; } else dr.style.display = 'none'; document.getElementById('cart-total').textContent = (sub - disc).toFixed(0) + ' ج.م'; }
async function applyCoupon() { const code = document.getElementById('coupon-inp').value.trim(); if (!code) return; const sub = S.cart.reduce((s, i) => s + i.price * i.qty, 0); try { const r = await fetch(`${API}/coupons/validate`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ code, subtotal: sub }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error); S.coupon = { code, ...data }; const msg = document.getElementById('coupon-msg'); msg.className = 'coupon-msg ok'; msg.textContent = `✓ خصم ${data.discount.toFixed(0)} ج.م`; updateTotals(); } catch (e) { const msg = document.getElementById('coupon-msg'); msg.className = 'coupon-msg err'; msg.textContent = e.message || 'الكود غلط'; S.coupon = null; updateTotals(); } }

/* ORDER */
function openOrderModal() { closeCart(); updateSum(); openModal('order-modal'); }
function setPay(t) { S.payMethod = t; document.getElementById('pay-cash').classList.toggle('on', t === 'cash'); document.getElementById('pay-online').classList.toggle('on', t === 'online'); }
function updateSum() { const gov = document.getElementById('of-gov')?.value; const sh = S.shipping.find(r => r.governorate === gov)?.price || 0; const sub = S.cart.reduce((s, i) => s + i.price * i.qty, 0); const disc = S.coupon ? (S.coupon.type === 'percent' ? sub * S.coupon.value / 100 : S.coupon.value) : 0; const total = sub + sh - disc; S._sh = sh; S._total = total; S._sub = sub; S._disc = disc; document.getElementById('sum-box').innerHTML = `<div class="sum-row"><span>المنتجات</span><span>${sub.toFixed(0)} ج.م</span></div><div class="sum-row"><span>الشحن</span><span>${sh.toFixed(0)} ج.م</span></div>${disc > 0 ? `<div class="sum-row" style="color:var(--green)"><span>خصم</span><span>${disc.toFixed(0)} ج.م-</span></div>` : ''}<div class="sum-total"><span>الإجمالي</span><span>${total.toFixed(0)} ج.م</span></div>`; }
async function placeOrder() { const name = document.getElementById('of-name').value.trim(); const phone = document.getElementById('of-phone').value.trim(); const gov = document.getElementById('of-gov').value; const addr = document.getElementById('of-addr').value.trim(); if (!name || !phone || !gov || !addr) { toast('من فضلك اكمل البيانات المطلوبة', 'err'); return; } if (!/^\d{10,15}$/.test(phone.replace(/\s/g, ''))) { toast('رقم الهاتف يجب 10-15 رقم', 'err'); return; } if (!S.cart.length) { toast('سلتك فارغة!', 'err'); return; } const btn = document.getElementById('place-btn'); btn.disabled = true; document.getElementById('place-lbl').textContent = t('placing'); try { const r = await fetch(`${API}/orders`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ customer_name: name, phone, phone2: document.getElementById('of-phone2').value || null, address: addr, governorate: gov, payment_method: S.payMethod, items: S.cart, subtotal: S._sub, shipping_cost: S._sh, discount: S._disc, coupon_code: S.coupon?.code || null, total: S._total }) }); const data = await r.json(); if (!data.success) throw new Error('فشل'); S.waData = { name, phone, items: S.cart, total: S._total, orderNum: data.order_number }; S.cart = []; S.coupon = null; saveCart(); updateBadges(); closeModal('order-modal'); document.getElementById('suc-num').textContent = data.order_number; document.getElementById('suc-title').textContent = t('suc_t'); document.getElementById('suc-msg').textContent = t('suc_m'); openModal('suc-modal'); } catch (e) { toast(e.message || 'خطأ، حاول تاني', 'err'); } finally { btn.disabled = false; document.getElementById('place-lbl').textContent = t('place'); } }
function sendWA() { const d = S.waData; if (!d) return; const wa = S.cfg.whatsapp1 || '201000000000'; const items = d.items.map(i => `• ${i.name}${i.color ? ' (' + i.color + ')' : ''}${i.size ? ' (' + i.size + ')' : ''} ×${i.qty} = ${(i.price * i.qty).toFixed(0)} ج.م`).join('\n'); window.open(`https://wa.me/${wa}?text=${encodeURIComponent(`🌊 *طلب جديد — الطوفان*\nرقم الطلب: *${d.orderNum}*\n\nالعميل: ${d.name}\nالتليفون: ${d.phone}\n\n*المنتجات:*\n${items}\n\n*الإجمالي: ${d.total.toFixed(0)} ج.م*`)}`, '_blank'); }
function openWA() { window.open(`https://wa.me/${S.cfg.whatsapp1 || '201000000000'}`, '_blank'); }

/* WISHLIST */
function quickWish(id) { const p = S.prods.find(x => x.id == id); if (!p) return; const idx = S.wish.findIndex(w => w.id == id); if (idx >= 0) S.wish.splice(idx, 1); else S.wish.push({ id: p.id, name_ar: p.name_ar, name_en: p.name_en, price: p.price, sku: p.sku, main_image: p.main_image }); localStorage.setItem('wish', JSON.stringify(S.wish)); updateBadges(); renderProds(S.prods); }
function openWishlist() { const base = API.replace('/api', ''); const el = document.getElementById('wish-items'); if (!S.wish.length) { el.innerHTML = `<p style="text-align:center;padding:40px;color:var(--text2)">${t('wish_empty')}</p>`; openModal('wish-modal'); return; } el.innerHTML = S.wish.map(p => { const name = S.lang === 'ar' ? p.name_ar : (p.name_en || p.name_ar); return `<div class="wi">${p.main_image ? `<img src="${base}${p.main_image}" alt="">` : `<div class="wi-ph">👕</div>`}<div style="flex:1;min-width:0"><div class="wi-name">${name}</div><div class="wi-price">${p.price} ج.م</div></div><button class="wi-add" onclick="closeModal('wish-modal');openProd(${p.id})">+ سلة</button><button class="wi-del" onclick="quickWish(${p.id});openWishlist()">🗑️</button></div>`; }).join(''); openModal('wish-modal'); }

/* AUTH */
function openAccount() { if (S.user) { renderAcc(); openModal('acc-modal'); } else openModal('auth-modal'); }
function loginDemo() { const u = { name: 'Demo User', email: 'demo@gmail.com' }; S.user = u; localStorage.setItem('user', JSON.stringify(u)); closeModal('auth-modal'); toast('تم تسجيل الدخول ✓', 'ok'); renderAcc(); openModal('acc-modal'); }
function logout() { S.user = null; localStorage.removeItem('user'); closeModal('acc-modal'); toast('تم تسجيل الخروج', 'info'); }
function renderAcc() { const u = S.user; document.getElementById('acc-info').innerHTML = `<span style="font-size:36px">👤</span><div><div style="font-weight:800;font-size:15px">${u.name}</div><div style="font-size:12px;color:var(--text2)">${u.email}</div></div>`; document.getElementById('acc-orders').innerHTML = `<p style="color:var(--text2);font-size:13px;text-align:center;padding:20px">اربط بالسيرفر لعرض طلباتك</p>`; }

/* CHATBOT */
const INTENTS = [{ keys: ['هاي', 'اهلا', 'مرحبا', 'سلام'], res: () => 'أهلاً وسهلاً بالطوفان! 🌊\nكيف أقدر أساعدك؟' }, { keys: ['منتج', 'عندكم', 'اقسام', 'ملابس'], res: async () => { try { const r = await fetch(`${API}/categories`); const c = await r.json(); const roots = c.filter(x => !x.parent_id); return 'عندنا:\n' + roots.map(x => '• ' + x.name_ar).join('\n'); } catch { return 'عندنا رجالي وحريمي وأطفال ورياضي 👕'; } } }, { keys: ['سعر', 'غالي', 'رخيص', 'تمن'], res: () => 'أسعارنا مناسبة جداً! 💰\nمن 200 ج.م للقطاعي' }, { keys: ['شحن', 'توصيل'], res: () => 'بنوصل لكل مصر 🚚\nبورسعيد شحن مجاني!' }, { keys: ['دفع', 'كاش', 'فيزا'], res: () => '💵 كاش عند الاستلام\n💳 أون لاين (فيزا)' }, { keys: ['جملة', 'تاجر'], res: () => 'أهلاً بالتجار! 📦\nتواصل معنا على واتساب' }, { keys: ['واتساب', 'تليفون', 'رقم'], res: () => `📱 ${S.cfg.whatsapp1 || '01000000000'}` }, { keys: ['شكرا', 'ممنون'], res: () => 'العفو! 😊 يسعدنا نساعدك' },];
function initChat() { addChatMsg('bot', 'أهلاً! أنا مساعد الطوفان 🌊\nاسألني عن أي حاجة!', ['المنتجات 👕', 'الشحن 🚚', 'الأسعار 💰']); }
function toggleChat() { document.getElementById('chatwin').classList.toggle('hide'); }
async function sendChat(text) { const inp = document.getElementById('chat-inp'); const msg = text || inp.value.trim(); if (!msg) return; if (!text) inp.value = ''; addChatMsg('user', msg); const lower = msg.toLowerCase(); const intent = INTENTS.find(i => i.keys.some(k => lower.includes(k))); if (intent) { const res = await intent.res(); setTimeout(() => addChatMsg('bot', res, ['المنتجات 👕', 'الشحن 🚚', 'الأسعار 💰']), 600); } else setTimeout(() => addChatMsg('bot', 'سؤالك وصلنا! 😊 تواصل على واتساب', ['التواصل 📱']), 700); }
function addChatMsg(type, text, opts = []) { const msgs = document.getElementById('chat-msgs'); const el = document.createElement('div'); el.className = `cmsg ${type}`; el.textContent = text; if (opts.length) { const d = document.createElement('div'); d.className = 'chat-opts'; opts.forEach(o => { const b = document.createElement('button'); b.className = 'copt'; b.textContent = o; b.onclick = () => sendChat(o); d.appendChild(b); }); el.appendChild(d); } msgs.appendChild(el); msgs.scrollTop = msgs.scrollHeight; }

/* UTILS */
function show(id) { document.getElementById(id).style.display = 'block'; }
function hide(id) { document.getElementById(id).style.display = 'none'; }
function openModal(id) { document.getElementById(id).classList.add('on'); }
function closeModal(id) { document.getElementById(id).classList.remove('on'); }
function updateBadges() { const cn = S.cart.reduce((s, i) => s + i.qty, 0); const cb = document.getElementById('cart-badge'); cb.textContent = cn; cb.style.display = cn > 0 ? 'flex' : 'none'; const wn = S.wish.length; const wb = document.getElementById('wish-badge'); wb.textContent = wn; wb.style.display = wn > 0 ? 'flex' : 'none'; }
function toast(msg, type = 'info') { const el = document.createElement('div'); el.className = `toast ${type}`; el.textContent = msg; document.getElementById('toast-wrap').appendChild(el); setTimeout(() => { el.style.opacity = '0'; el.style.transition = '.3s'; setTimeout(() => el.remove(), 300); }, 2800); }
window.addEventListener('click', e => { document.querySelectorAll('.modal-bg.on').forEach(m => { if (e.target === m) m.classList.remove('on'); }); });
if ('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(() => { });
